### ISSUE TITLE
responseWriterImpl  does not implement http.Hijacker

### ISSUE THREAD

**Issue by lufishggg** [sqreen/go-agent#134]
responseWriterImpl  does not implement http.Hijacker, which will cause websocket connect error if middleware is used.

**Comment by Julio-Guerra** [comment]
We currently don't support websockets. This is planned for later this year or early next year.

For the record, what websocket package are you using?

**Comment by lufishggg** [comment]
The package we use is github.com/gorilla/websocket. Actually we are now using graphql(https://github.com/graph-gophers/graphql-go, https://github.com/graph-gophers/graphql-transport-ws).So there is a little not convenient for us to use qhttp.Middleware in the router, because for graphql, the endpoint is the same for both websocket(subscription) and http request.

**Comment by Julio-Guerra** [comment]
Hello @lufishggg,
#170 adds support for it. Please note that even if this PR brings all the support required to make our HTTP middleware work with graphql/websocket, our blocking HTTP response is currently an HTML page. Make sure to check your graphQL client will correctly work with it. Please let us if otherwise.

**Comment by Julio-Guerra** [comment]
FYI, I ran a quick test using `gorilla/websocket`, and everything works fine. But note that we are currently limited to the HTTP layer, and the agent is currently blind regarding websocket requests.
